sudo: true
language: scala
dist: trusty  # Temporarily force dist
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - scala: 2.12.2
      jdk: oraclejdk7
addons:
  firefox: latest
  chrome: stable
before_install:
  # Initilize xvfb
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install Selenium drivers
  - wget http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - tar xf geckodriver-v0.18.0-linux64.tar.gz -C bin
  - export PATH=$PWD/bin:$PATH
before_script:
  - python -m SimpleHTTPServer 8080 &
script:
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    seleniumJSEnv/scalastyle
    seleniumJSEnv/test:scalastyle
    seleniumJSEnvTest/scalastyle
    seleniumJSHttpEnvTest/test:scalastyle
    seleniumJSEnvTest/test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION seleniumJSEnv/mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION seleniumJSEnv/test
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    seleniumJSEnvTest/run
    seleniumJSEnvTest/test
    'set scalaJSStage in Global := FullOptStage'
    seleniumJSEnvTest/run
    seleniumJSEnvTest/test
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    seleniumJSHttpEnvTest/test
    'set scalaJSStage in Global := FullOptStage'
    seleniumJSHttpEnvTest/test
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    'set jsEnvCapabilities in seleniumJSEnvTest := org.openqa.selenium.remote.DesiredCapabilities.chrome()'
    seleniumJSEnvTest/run
    seleniumJSEnvTest/test
    'set scalaJSStage in Global := FullOptStage'
    seleniumJSEnvTest/run
    seleniumJSEnvTest/test
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    'set jsEnvCapabilities in seleniumJSHttpEnvTest := org.openqa.selenium.remote.DesiredCapabilities.chrome()'
    seleniumJSHttpEnvTest/test
    'set scalaJSStage in Global := FullOptStage'
    seleniumJSHttpEnvTest/test
