sudo: true
language: scala
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
env:
  - SJS_TEST_BROWSER=firefox
matrix:
  include:
    - scala: 2.12.2
      jdk: oraclejdk8
      env: SJS_TEST_BROWSER=chrome
addons:
  firefox: latest
  chrome: stable
before_install:
  # Install Selenium drivers
  - wget http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d bin
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar xf geckodriver-v0.24.0-linux64.tar.gz -C bin
  - export PATH=$PWD/bin:$PATH
before_script:
  - python -m SimpleHTTPServer 8080 &
script:
  - >
    sbt ++$TRAVIS_SCALA_VERSION
    seleniumJSEnv/scalastyle
    seleniumJSEnv/test:scalastyle
    seleniumJSEnvTest/scalastyle
    seleniumJSHttpEnvTest/test:scalastyle
    seleniumJSEnvTest/test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION seleniumJSEnv/mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION seleniumJSEnv/test
  - >
    if [[ $TRAVIS_SCALA_VERSION != 2.10.* ]]; then
      sbt ++$TRAVIS_SCALA_VERSION \
      seleniumJSEnvTest/test \
      'set scalaJSStage in Global := FullOptStage' \
      seleniumJSEnvTest/test;
    fi
  - >
    if [[ $TRAVIS_SCALA_VERSION != 2.10.* ]]; then
      sbt ++$TRAVIS_SCALA_VERSION \
      seleniumJSHttpEnvTest/test \
      'set scalaJSStage in Global := FullOptStage' \
      seleniumJSHttpEnvTest/test;
    fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
